# Learning and Decision Making

## Laboratory 3: Markov decision problems

In the end of the lab, you should submit all code/answers written in the tasks marked as "Activity n. XXX", together with the corresponding outputs and any replies to specific questions posed to the e-mail <adi.tecnico@gmail.com>. Make sure that the subject is of the form [&lt;group n.&gt;] LAB &lt;lab n.&gt;.

### 1. Modeling

Consider once again the predator-prey domain described in the Homework and which you described as a Markov decision process.

<img src="toroidal-world.png" width="400px">

Recall that:

* toroidal world "wraps around", i.e., an individual exiting through any of the four sides of the grid reenters on the opposite side (see figure above).

* At each time step, the hare selects uniformly at random one of the four directions (up, down, left, and right) and moves to the adjacent cell in that direction with a probability 0.4. With a probability 0.6 it remains in the same cell. 

* The wolf, on the other hand, can select at each time step one of five actions---up (_U_), down (_D_), left (_L_) and right (_R_) or stay (_S_). If it selects action _S_, it remains in the same cell with probability 1.0. Otherwise, the other 4 actions succeed in moving the wolf to the adjacent cell in the corresponding direction with a probability 0.8 and fail with a probability 0.2. 

* The goal of the wolf is to catch the hare.

---

#### Activity 1.        

Implement your Markov decision process in Python. In particular,

* Create a list with all the states;
* Create a list with all the actions;
* For each action, define a `numpy` array with the corresponding transition probabilities;
* Define a `numpy`array with the costs

The order for the states and actions used in the transition probability and cost matrices should match that in the lists of states and actions. 

**Note 1**: Don't forget to import `numpy`.

**Note 2**: You can define the transition probability matrices for each of the two individuals and then build the combined transition probability matrices using the `numpy.kron` function.

---

In [1]:
import numpy as np

P_Up = np.array([[0.12,0.04,0.04,0.  ,0.  ,0.  ,0.  ,0.  ,0.48, 0.16,0.16,0.  ,0.  ,0.  ,0.  ,0.  ],
                 [0.04,0.12,0.  ,0.04,0.  ,0.  ,0.  ,0.  ,0.16, 0.48,0.  ,0.16,0.  ,0.  ,0.  ,0.  ],
                 [0.04,0.  ,0.12,0.04,0.  ,0.  ,0.  ,0.  ,0.16, 0.  ,0.48,0.16,0.  ,0.  ,0.  ,0.  ],
                 [0.  ,0.04,0.04,0.12,0.  ,0.  ,0.  ,0.  ,0.  , 0.16,0.16,0.48,0.  ,0.  ,0.  ,0.  ],
                 [0.  ,0.  ,0.  ,0.  ,0.12,0.04,0.04,0.  ,0.  , 0.  ,0.  ,0.  ,0.48,0.16,0.16,0.  ],
                 [0.  ,0.  ,0.  ,0.  ,0.04,0.12,0.  ,0.04,0.  , 0.  ,0.  ,0.  ,0.16,0.48,0.  ,0.16],
                 [0.  ,0.  ,0.  ,0.  ,0.04,0.  ,0.12,0.04,0.  , 0.  ,0.  ,0.  ,0.16,0.  ,0.48,0.16],
                 [0.  ,0.  ,0.  ,0.  ,0.  ,0.04,0.04,0.12,0.  , 0.  ,0.  ,0.  ,0.  ,0.16,0.16,0.48],
                 [0.48,0.16,0.16,0.  ,0.  ,0.  ,0.  ,0.  ,0.12, 0.04,0.04,0.  ,0.  ,0.  ,0.  ,0.  ],
                 [0.16,0.48,0.  ,0.16,0.  ,0.  ,0.  ,0.  ,0.04, 0.12,0.  ,0.04,0.  ,0.  ,0.  ,0.  ],
                 [0.16,0.  ,0.48,0.16,0.  ,0.  ,0.  ,0.  ,0.04, 0.  ,0.12,0.04,0.  ,0.  ,0.  ,0.  ],
                 [0.  ,0.16,0.16,0.48,0.  ,0.  ,0.  ,0.  ,0.  , 0.04,0.04,0.12,0.  ,0.  ,0.  ,0.  ],
                 [0.  ,0.  ,0.  ,0.  ,0.48,0.16,0.16,0.  ,0.  , 0.  ,0.  ,0.  ,0.12,0.04,0.04,0.  ],
                 [0.  ,0.  ,0.  ,0.  ,0.16,0.48,0.  ,0.16,0.  , 0.  ,0.  ,0.  ,0.04,0.12,0.  ,0.04],
                 [0.  ,0.  ,0.  ,0.  ,0.16,0.  ,0.48,0.16,0.  , 0.  ,0.  ,0.  ,0.04,0.  ,0.12,0.04],
                 [0.  ,0.  ,0.  ,0.  ,0.  ,0.16,0.16,0.48,0.  , 0.  ,0.  ,0.  ,0.  ,0.04,0.04,0.12]])

P_Down = np.array([[0.12,0.04,0.04,0.  ,0.  ,0.  ,0.  ,0.  ,0.48, 0.16,0.16,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.04,0.12,0.  ,0.04,0.  ,0.  ,0.  ,0.  ,0.16, 0.48,0.  ,0.16,0.  ,0.  ,0.  ,0.  ],
                   [0.04,0.  ,0.12,0.04,0.  ,0.  ,0.  ,0.  ,0.16, 0.  ,0.48,0.16,0.  ,0.  ,0.  ,0.  ],
                   [0.  ,0.04,0.04,0.12,0.  ,0.  ,0.  ,0.  ,0.  , 0.16,0.16,0.48,0.  ,0.  ,0.  ,0.  ],
                   [0.  ,0.  ,0.  ,0.  ,0.12,0.04,0.04,0.  ,0.  , 0.  ,0.  ,0.  ,0.48,0.16,0.16,0.  ],
                   [0.  ,0.  ,0.  ,0.  ,0.04,0.12,0.  ,0.04,0.  , 0.  ,0.  ,0.  ,0.16,0.48,0.  ,0.16],
                   [0.  ,0.  ,0.  ,0.  ,0.04,0.  ,0.12,0.04,0.  , 0.  ,0.  ,0.  ,0.16,0.  ,0.48,0.16],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.04,0.04,0.12,0.  , 0.  ,0.  ,0.  ,0.  ,0.16,0.16,0.48],
                   [0.48,0.16,0.16,0.  ,0.  ,0.  ,0.  ,0.  ,0.12, 0.04,0.04,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.16,0.48,0.  ,0.16,0.  ,0.  ,0.  ,0.  ,0.04, 0.12,0.  ,0.04,0.  ,0.  ,0.  ,0.  ],
                   [0.16,0.  ,0.48,0.16,0.  ,0.  ,0.  ,0.  ,0.04, 0.  ,0.12,0.04,0.  ,0.  ,0.  ,0.  ],
                   [0.  ,0.16,0.16,0.48,0.  ,0.  ,0.  ,0.  ,0.  , 0.04,0.04,0.12,0.  ,0.  ,0.  ,0.  ],
                   [0.  ,0.  ,0.  ,0.  ,0.48,0.16,0.16,0.  ,0.  , 0.  ,0.  ,0.  ,0.12,0.04,0.04,0.  ],
                   [0.  ,0.  ,0.  ,0.  ,0.16,0.48,0.  ,0.16,0.  , 0.  ,0.  ,0.  ,0.04,0.12,0.  ,0.04],
                   [0.  ,0.  ,0.  ,0.  ,0.16,0.  ,0.48,0.16,0.  , 0.  ,0.  ,0.  ,0.04,0.  ,0.12,0.04],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.16,0.16,0.48,0.  , 0.  ,0.  ,0.  ,0.  ,0.04,0.04,0.12]])

P_Left = np.array([[0.12,0.04,0.04,0.  ,0.48,0.16,0.16,0.  ,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.04,0.12,0.  ,0.04,0.16,0.48,0.  ,0.16,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.04,0.  ,0.12,0.04,0.16,0.  ,0.48,0.16,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.  ,0.04,0.04,0.12,0.  ,0.16,0.16,0.48,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.48,0.16,0.16,0.  ,0.12,0.04,0.04,0.  ,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.16,0.48,0.  ,0.16,0.04,0.12,0.  ,0.04,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.16,0.  ,0.48,0.16,0.04,0.  ,0.12,0.04,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.  ,0.16,0.16,0.48,0.  ,0.04,0.04,0.12,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.12, 0.04,0.04,0.  ,0.48,0.16,0.16,0.  ],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.04, 0.12,0.  ,0.04,0.16,0.48,0.  ,0.16],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.04, 0.  ,0.12,0.04,0.16,0.  ,0.48,0.16],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  , 0.04,0.04,0.12,0.  ,0.16,0.16,0.48],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.48, 0.16,0.16,0.  ,0.12,0.04,0.04,0.  ],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.16, 0.48,0.  ,0.16,0.04,0.12,0.  ,0.04],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.16, 0.  ,0.48,0.16,0.04,0.  ,0.12,0.04],
                   [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  , 0.16,0.16,0.48,0.  ,0.04,0.04,0.12]])

P_Right = np.array([[0.12,0.04,0.04,0.  ,0.48,0.16,0.16,0.  ,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                    [0.04,0.12,0.  ,0.04,0.16,0.48,0.  ,0.16,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                    [0.04,0.  ,0.12,0.04,0.16,0.  ,0.48,0.16,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                    [0.  ,0.04,0.04,0.12,0.  ,0.16,0.16,0.48,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                    [0.48,0.16,0.16,0.  ,0.12,0.04,0.04,0.  ,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                    [0.16,0.48,0.  ,0.16,0.04,0.12,0.  ,0.04,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                    [0.16,0.  ,0.48,0.16,0.04,0.  ,0.12,0.04,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                    [0.  ,0.16,0.16,0.48,0.  ,0.04,0.04,0.12,0.  , 0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ],
                    [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.12, 0.04,0.04,0.  ,0.48,0.16,0.16,0.  ],
                    [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.04, 0.12,0.  ,0.04,0.16,0.48,0.  ,0.16],
                    [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.04, 0.  ,0.12,0.04,0.16,0.  ,0.48,0.16],
                    [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  , 0.04,0.04,0.12,0.  ,0.16,0.16,0.48],
                    [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.48, 0.16,0.16,0.  ,0.12,0.04,0.04,0.  ],
                    [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.16, 0.48,0.  ,0.16,0.04,0.12,0.  ,0.04],
                    [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.16, 0.  ,0.48,0.16,0.04,0.  ,0.12,0.04],
                    [0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  ,0.  , 0.16,0.16,0.48,0.  ,0.04,0.04,0.12]])

P_Stay = np.array([[ 0.6,0.2,0.2,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. , 0. ,0. ,0. ,0. ,0. ],
                   [ 0.2,0.6,0. ,0.2,0. ,0. ,0. ,0. ,0. ,0. ,0. , 0. ,0. ,0. ,0. ,0. ],
                   [ 0.2,0. ,0.6,0.2,0. ,0. ,0. ,0. ,0. ,0. ,0. , 0. ,0. ,0. ,0. ,0. ],
                   [ 0. ,0.2,0.2,0.6,0. ,0. ,0. ,0. ,0. ,0. ,0. , 0. ,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0.6,0.2,0.2,0. ,0. ,0. ,0. , 0. ,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0.2,0.6,0. ,0.2,0. ,0. ,0. , 0. ,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0.2,0. ,0.6,0.2,0. ,0. ,0. , 0. ,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0. ,0.2,0.2,0.6,0. ,0. ,0. , 0. ,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0.6,0.2,0.2, 0. ,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0.2,0.6,0. , 0.2,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0.2,0. ,0.6, 0.2,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0.2,0.2, 0.6,0. ,0. ,0. ,0. ],
                   [ 0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. , 0. ,0.6,0.2,0.2,0. ],
                   [ 0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. , 0. ,0.2,0.6,0. ,0.2],
                   [ 0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. , 0. ,0.2,0. ,0.6,0.2],
                   [ 0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. ,0. , 0. ,0. ,0.2,0.2,0.6]])




#FALTA LISTA DE ACCOES

#FALTA LISTA DE ESTADOS



###################################################################
###############  Matrix de Custo   ################################
###################################################################

same_position_state_indexes = [0, 5, 10, 15]

above_bellow_position_state_indexes = [2, 7, 8, 13]

left_right_position_state_indexes = [1, 4, 11, 14]

diagonal_position_state_indexes = [3, 6, 9, 12]

stay = 4

up_or_down = [0, 1]

left_or_right = [2, 3]

def build_cost_matrix():
    costMatrix = np.zeros((16, 5))
    for possible_action in range(5):
        for possible_state in range(16):
            if possible_state in same_position_state_indexes and possible_action == stay:
                costMatrix[possible_state, possible_action] = 0
                
            elif possible_state in above_bellow_position_state_indexes and possible_action in up_or_down:
                costMatrix[possible_state, possible_action] = 0
            
            elif possible_state in left_right_position_state_indexes and possible_action in left_or_right:
                costMatrix[possible_state, possible_action] = 0
                
            elif possible_state in diagonal_position_state_indexes and possible_action != stay:
                costMatrix[possible_state, possible_action] = 0
                
            else:
                costMatrix[possible_state, possible_action] = 1
                
    return costMatrix

build_cost_matrix()





array([[ 1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  0.]])

### 2. Prediction

You are now going to evaluate a given policy, computing the corresponding cost-to-go.

---

#### Activity 2.

Describe the policy that, in each state $(w, h)$, always moves the wolf to the cell closest to the hare. If multiple such cells exist, the wolf should select randomly between the two.

For example, suppose that the wolf is in cell 1 and the hare in cell 4 (figure above, left). The wolf should then select randomly between the actions _U_, _D_ (which move the wolf to cell 3), _L_ and _R_ (which move the wolf to cell 2). Conversely, if the wolf is in cell 1 and the hare in cell 3 (figure above, right), the wolf should select randomly between the two actions _U_ and _D_ (which move the wolf to cell 3).

**Note:** The policy should be described as a vector with as many rows as there are states and as many columns as there are actions, where the entry _xa_ has the probability of selecting action _a_ in state _x_.

---

In [2]:
import numpy as np

same_position_state_indexes = [0, 5, 10, 15]

above_bellow_position_state_indexes = [2, 7, 8, 13]

left_right_position_state_indexes = [1, 4, 11, 14]

diagonal_position_state_indexes = [3, 6, 9, 12]

stay = 4

up_or_down = [0, 1]

left_or_right = [2, 3]

def build_policy_matrix():
    policyMatrix = np.zeros((16, 5))
    for possible_action in range(5):
        for possible_state in range(16):
            if possible_state in same_position_state_indexes and possible_action == stay:
                policyMatrix[possible_state, possible_action] = 1
                
            elif possible_state in above_bellow_position_state_indexes and possible_action in up_or_down:
                policyMatrix[possible_state, possible_action] = 0.5
            
            elif possible_state in left_right_position_state_indexes and possible_action in left_or_right:
                policyMatrix[possible_state, possible_action] = 0.5
                
            elif possible_state in diagonal_position_state_indexes and possible_action != stay:
                policyMatrix[possible_state, possible_action] = 0.25
                
            else:
                policyMatrix[possible_state, possible_action] = 0
                
    return policyMatrix

build_policy_matrix()








array([[ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.5 ,  0.5 ,  0.  ],
       [ 0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ],
       [ 0.25,  0.25,  0.25,  0.25,  0.  ],
       [ 0.  ,  0.  ,  0.5 ,  0.5 ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ],
       [ 0.25,  0.25,  0.25,  0.25,  0.  ],
       [ 0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ],
       [ 0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ],
       [ 0.25,  0.25,  0.25,  0.25,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.5 ,  0.5 ,  0.  ],
       [ 0.25,  0.25,  0.25,  0.25,  0.  ],
       [ 0.5 ,  0.5 ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.5 ,  0.5 ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ]])

---

#### Activity 3.

Compute the cost-to-go function $J^\pi$ associated with the policy from Activity 2. Use $\gamma=0.99$.

---

In [3]:
import numpy as np
from numpy.linalg import inv


ident = np.eye(16)


gamma = 0.99

pi = build_policy_matrix() # politica inicial

# USAMOS ESTA OU PODEMOS USAR A NOSSA ?
costMatrix = np.array([[0,0,0,0,0],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],
                       [0,0,0,0,0],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],
                       [0,0,0,0,0],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],
                       [0,0,0,0,0]])

def calc_cost_to_go():
    
    c_Up = costMatrix[:,0][np.newaxis, :].T
    c_Down = costMatrix[:,0][np.newaxis, :].T
    c_Left = costMatrix[:,2][np.newaxis, :].T
    c_Right = costMatrix[:,2][np.newaxis, :].T
    c_Stay = costMatrix[:,4][np.newaxis, :].T
    
        
    p_Up = P_Up 
    p_Down = P_Down 
    p_Left = P_Left
    p_Right = P_Right
    p_Stay = P_Stay
    

    
    Ppi = np.diag(pi[:,0]).dot(p_Up) + \
          np.diag(pi[:,1]).dot(p_Down) + \
          np.diag(pi[:,2]).dot(p_Left) + \
          np.diag(pi[:,3]).dot(p_Right) + \
          np.diag(pi[:,4]).dot(p_Stay)
    
    Cpi = np.diag(pi[:,0]).dot(c_Up) + \
          np.diag(pi[:,1]).dot(c_Down) + \
          np.diag(pi[:,2]).dot(c_Left) + \
          np.diag(pi[:,3]).dot(c_Right) + \
          np.diag(pi[:,4]).dot(c_Stay)
                
    
    J = np.linalg.inv(np.eye(16) - gamma * Ppi).dot(Cpi)
    
    return J
        
    
#######################
calc_cost_to_go()




array([[ 43.88841893],
       [ 44.99671233],
       [ 44.99671233],
       [ 45.51480752],
       [ 44.99671233],
       [ 43.88841893],
       [ 45.51480752],
       [ 44.99671233],
       [ 44.99671233],
       [ 45.51480752],
       [ 43.88841893],
       [ 44.99671233],
       [ 45.51480752],
       [ 44.99671233],
       [ 44.99671233],
       [ 43.88841893]])

### 3. Control

In this section you are going to compare value and policy iteration, both in terms of time and number of iterations.

---

#### Activity 4

Show that the policy in Activity 3 is optimal: use value iteration to compute $J^*$ and show that $J^*=J^\pi$. Track the time and the number of iterations taken to compute $J^*$.

**Note 1:** Stop the algorithm when the error between iterations is smaller than $10^{-8}$.

**Note 2:** You may find useful the function ``time()`` from the module ``time``.

---

In [4]:
import numpy as np
import timeit

np.set_printoptions(precision=3)

iteration = 0

policy_J_optimal = np.zeros((16,1))



def calc_val_iter():
    
    # o [np.newaxis, :].T e uma forma estranha de transpor porque o .T apenas nao tava a dar
    c_UpDown = costMatrix[:,0][np.newaxis, :].T
    c_LeftRight = costMatrix[:,2][np.newaxis, :].T
    c_Stay = costMatrix[:,4][np.newaxis, :].T
    
    p_UpDown = P_Up
    p_LeftRight = P_Left
    p_Stay = P_Stay

    gamma = 0.99

    J = np.zeros((16,1))
    err = 1
    
    while err > 1e-8:
        

        q_UpDown = c_UpDown + gamma * p_UpDown.dot(J)
        q_LeftRight = c_LeftRight + gamma * p_LeftRight.dot(J)
        q_Stay = c_Stay + gamma * p_Stay.dot(J)

       
        Jnew = np.min((q_UpDown, q_LeftRight, q_Stay), axis=0)

        err = np.linalg.norm(Jnew - J)
        
        global iteration
        iteration += 1
        J = Jnew
    
    
    
    global policy_J_optimal
    policy_J_optimal = J
################################

# TEM DE DEVOLVER UM VECTOR
 
calc_val_iter()   
print("Iterations: "+ str(iteration))
print("\n")
print("Tempo: " + str(timeit.timeit(calc_val_iter, number=1)))
print("\n")
print(policy_J_optimal)
print("\n")




Iterations: 1891


Tempo: 0.198271069364


[[ 43.888]
 [ 44.997]
 [ 44.997]
 [ 45.515]
 [ 44.997]
 [ 43.888]
 [ 45.515]
 [ 44.997]
 [ 44.997]
 [ 45.515]
 [ 43.888]
 [ 44.997]
 [ 45.515]
 [ 44.997]
 [ 44.997]
 [ 43.888]]




---

#### Activity 5

Compute once again the optimal policy now using policy iteration. Track the time and number of iterations taken and compare to those of Activity 4.

**Note:** If you find that numerical errors affect your computations (especially when comparing two values/arrays) you may use the `numpy` function `isclose` with adequately set absolute and relative tolerance parameters (e.g., $10^{-8}$).

---

In [5]:
import numpy as np
import timeit

np.set_printoptions(precision=3)

iteration = 0

policy_J_optimal = np.zeros((16,16))

def calc_pol_iter():
    
    c_Up = costMatrix[:,0]
    c_Down = costMatrix[:,0]
    c_Left = costMatrix[:,2]
    c_Right = costMatrix[:,2]
    c_Stay = costMatrix[:,4]
        
    p_Up = P_Up 
    p_Down = P_Down 
    p_Left = P_Left
    p_Right = P_Right
    p_Stay = P_Stay

    gamma = 0.99
    
    pi = build_policy_matrix() # politica inicial
    pi =  np.array([[0.  , 0.  , 0.  , 0.15, 0.75],
                    [0.  , 0.  , 0.5 , 0.5 , 0.  ],
                    [0.5 , 0.5 , 0.  , 0.  , 0.  ],
                    [0.0 , 0.0 , 0.5 , 0.5 , 0.  ],
                    [0.  , 0.  , 0.5 , 0.5 , 0.  ],
                    [0.  , 0.25, 0.25, 0.25, 0.25],
                    [0.25, 0.25, 0.25, 0.25, 0.  ],
                    [0.30, 0.67, 0.03, 0.00, 0.00],
                    [0.25, 0.25, 0.25, 0.25, 0.  ],
                    [0.25, 0.25, 0.25, 0.25, 0.  ],
                    [0.94, 0.03, 0.01, 0.00, 0.0 ],
                    [0.  , 0.  , 0.5 , 0.5 , 0.  ],
                    [0.25, 0.25, 0.25, 0.25, 0.  ],
                    [0.25, 0.25, 0.25, 0.25, 0.  ],
                    [0.  , 0.  , 0.75, 0.15, 0.  ],
                    [0.  , 0.5 , 0.  , 0.  , 0.5 ]])
    
    quit = False 

    #"up","down","left","right,"stay"
    
    while not quit:
        

        Cpi = np.diag(pi[:,0]).dot(c_Up) + \
              np.diag(pi[:,1]).dot(c_Down) + \
              np.diag(pi[:,2]).dot(c_Left) + \
              np.diag(pi[:,3]).dot(c_Right) + \
              np.diag(pi[:,4]).dot(c_Stay)
                
        Ppi = np.diag(pi[:,0]).dot(p_Up) + \
              np.diag(pi[:,1]).dot(p_Down) + \
              np.diag(pi[:,2]).dot(p_Left) + \
              np.diag(pi[:,3]).dot(p_Right) + \
              np.diag(pi[:,4]).dot(p_Stay)
                
        J = np.linalg.inv(np.eye(16) - gamma * Ppi).dot(Cpi)
        
        
        
        Qup = c_Up + gamma * p_Up.dot(J)
        Qdown = c_Down + gamma * p_Down.dot(J)
        Qleft = c_Left + gamma * p_Left.dot(J)
        Qright = c_Right + gamma * p_Right.dot(J)
        Qstay = c_Stay + gamma * p_Stay.dot(J)
        
        
        pinew = np.zeros((16,5))
        
        
        pinew[:,0] = np.isclose(Qup, np.min([Qup, Qdown, Qleft, Qright, Qstay], axis=0), atol=1e-10, rtol=1e-10).astype(int)
        pinew[:,1] = np.isclose(Qdown, np.min([Qup, Qdown, Qleft, Qright, Qstay], axis=0), atol=1e-10, rtol=1e-10).astype(int)
        pinew[:,2] = np.isclose(Qleft, np.min([Qup, Qdown, Qleft, Qright, Qstay], axis=0), atol=1e-10, rtol=1e-10).astype(int)
        pinew[:,3] = np.isclose(Qright, np.min([Qup, Qdown, Qleft, Qright, Qstay], axis=0), atol=1e-10, rtol=1e-10).astype(int)
        pinew[:,4] = np.isclose(Qstay, np.min([Qup, Qdown, Qleft, Qright, Qstay], axis=0), atol=1e-10, rtol=1e-10).astype(int)
    
        pinew = pinew / np.sum(pinew, axis=1, keepdims = True)
        
        quit = (pi == pinew).all()
        pi = pinew
        
        global iteration
        iteration += 1
    
    global policy_J_optimal
    policy_J_optimal = pi
    
calc_pol_iter()
print("Iterations: "+ str(iteration))
print("\n")
print("Tempo: " + str(timeit.timeit(calc_pol_iter, number=1)))
print("\n")
print(policy_J_optimal)


Iterations: 4


Tempo: 0.00518704850141


[[ 0.    0.    0.    0.    1.  ]
 [ 0.    0.    0.5   0.5   0.  ]
 [ 0.5   0.5   0.    0.    0.  ]
 [ 0.25  0.25  0.25  0.25  0.  ]
 [ 0.    0.    0.5   0.5   0.  ]
 [ 0.    0.    0.    0.    1.  ]
 [ 0.25  0.25  0.25  0.25  0.  ]
 [ 0.5   0.5   0.    0.    0.  ]
 [ 0.5   0.5   0.    0.    0.  ]
 [ 0.25  0.25  0.25  0.25  0.  ]
 [ 0.    0.    0.    0.    1.  ]
 [ 0.    0.    0.5   0.5   0.  ]
 [ 0.25  0.25  0.25  0.25  0.  ]
 [ 0.5   0.5   0.    0.    0.  ]
 [ 0.    0.    0.5   0.5   0.  ]
 [ 0.    0.    0.    0.    1.  ]]


### 4. Simulation

Finally, in this section you will check whether the theoretical computations of the cost-to-go actually correspond to the cost incurred by an agent following a policy.

---

#### Activity 6

Starting in each of the two states $x$ in the initial figure, 

* Generate **100** trajectories of 10,000 steps each, following the optimal policy for the MDP. 
* For each trajectory, compute the accumulated (discounted) cost. 
* Compute the average cost over the 100 trajectories.
* Compare the resulting value with that computed in Activity 4 for the two states. 

** Note:** The simulation may take a bit of time, don't despair ☺️.

---

In [ ]:
import numpy.random as rnd 

trajectories = []
discountedCost= []

t=0 #100
s=0 #10000

##probailites when choosing an action
wolfP =[0.8, 0.2] #[move, stay]
hareP =[0.4, 0.6] #[move, stay]
a= ["M" , "S"]

def moveUpDown(actualpos):
    return{
        1: 3,
        2: 4,
        3: 1,
        4: 2,
    }[actualpos]

def moveLeftRight(actualpos):
    return{
        1: 2,
        2: 1,
        3: 4,
        4: 3,
    }[actualpos] 
        
    
    
while t<2:  #100
    
    init = (1,4)
    s=0
    nextPos = (1, 4)
    trajectory=[nextPos]
    while s<10: # 10000
        
        #print nextPos
        
        #print "===hare==="
        ####MOVE HARE
        #random action
        nextMoveHare= rnd.randint(1, 5)
        #print "action"
        #print nextMoveHare
        
        #probability of moving
        resultH= np.random.choice(a,1, replace=False, p=hareP)  
        #print "probability action"
        #print  resultH
       
        if resultH!=["S"]:
            if nextMoveHare == 1 or nextMoveHare == 2:
                afterHare = (nextPos[0], moveUpDown(nextPos[1]))
            else:
                afterHare = (nextPos[0], moveLeftRight(nextPos[1]))
        else:
            afterHare = nextPos
        
        #print afterHare
        
        
        ##state 
        #print "=state="
        stateIdx=states.index(afterHare)
        state= states[stateIdx]        
        #print stateIdx
        #print state
         
        #print "===wolf==="
    
        ####MOVE WOLF
        #print policy_J_optimal[stateIdx]
        nextMoveV = max(policy_J_optimal[stateIdx])
        #print nextMoveV
        
        if nextMoveV!=1:
            resultW= np.random.choice(a,1, replace=False, p=wolfP) 
            
            #print resultW
            if resultW!=["S"]:
            
                if nextMoveV==0.25:
                    nextMoveWolf= rnd.randint(1, 5)                           
                elif policy_J_optimal[stateIdx][0]==0.5:
                    
                    nextMoveWolf= rnd.randint(1, 3)
                else:
                    nextMoveWolf= rnd.randint(3, 5)
                
                #print nextMoveWolf
                if nextMoveWolf == 1 or nextMoveWolf == 2:
                    afterWolf = (moveUpDown(state[0]), state[1])
                
                else:
                    afterWolf = (moveLeftRight(state[0]), state[1])
                
                
            else:
                afterWolf= state
                            
        else:
            afterWolf= state
        
        
        #print afterWolf
        #print "\n"
        
    
        #nextPos = final
        nextPos = afterWolf
        trajectory+=[nextPos]
                
        #count discounted cost
        s=s+1
        
    t=t+1
    trajectories += [trajectory]
    
for i in trajectories:
    print i
    print "\n"




In [143]:






pi = np.array([[1,1,1]])
px = np.array([[0,0,0]])
pA = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(pi)
print(pA.dot(px.T))
print(pi + pA.dot(px.T))

#print(c_Up[np.newaxis, :].T)

[[1 1 1]]
[[0]
 [0]
 [0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [152]:
import numpy as np
import timeit

np.set_printoptions(precision=3)

iteration = 0

policy_J_optimal = np.zeros((16,1))

def calc_val_iter():
    
    c_A = np.array([[1],[0],[1]])
    c_B = np.array([[0.5],[0],[1]])
        
    p_A = np.array([[0, 1, 0],[0, 1, 0],[0, 0, 1]])
    p_B = np.array([[0, 0, 1],[0, 1, 0],[0, 0, 1]])


    gamma = 0.99

    J = np.zeros((3,1))
    err = 1
   
    print(c_A)
    print(p_A.dot(J))
    
    while err > 1e-8:
        
       
        
        q_A = c_A + gamma * p_A.dot(J)
        q_B = c_B + gamma * p_B.dot(J)

        
        Jnew = np.min((q_A, q_B), axis=0)
        err = np.linalg.norm(Jnew - J)
        
        global iteration
        iteration += 1
        J = Jnew
    
    
    
    global policy_J_optimal
    policy_J_optimal = J
################################

# TEM DE DEVOLVER UM VECTOR
 
calc_val_iter()   
print("Iterations: "+ str(iteration))
print("\n")
print("Tempo: " + str(timeit.timeit(calc_val_iter, number=1)))
print("\n")
print(policy_J_optimal)
print("\n")

[[1]
 [0]
 [1]]
[[ 0.]
 [ 0.]
 [ 0.]]
Iterations: 1834


[[1]
 [0]
 [1]]
[[ 0.]
 [ 0.]
 [ 0.]]
Tempo: 0.188813485485


[[  1.]
 [  0.]
 [100.]]




In [24]:
import random

precision = 1000000

def f(n) :
    matrix = []
    for l in range(n) :
        lineLst = []
        sum = 0
        crtPrec = precision
        for i in range(n-1) :
            val = random.randrange(crtPrec)
            sum += val
            lineLst.append(float(val)/precision)
            crtPrec -= val
        lineLst.append(float(precision - sum)/precision)
        matrix.append(lineLst)
    return matrix


matrix = f(5)
print matrix

[[0.760306, 0.06057, 0.156509, 0.016456, 0.006159], [0.503486, 0.024194, 0.462175, 0.00939, 0.000755], [0.643254, 0.285741, 0.003296, 0.049602, 0.018107], [0.301946, 0.675062, 0.017749, 0.00512, 0.000123], [0.185646, 0.653316, 0.060583, 0.045149, 0.055306]]


In [87]:
def setup_possible_states():
    possible_states = []
    for row in range(4):
        for column in range(4):
            current_state = (row+1, column+1)
            possible_states.append(current_state)
    return possible_states

# Diz onde vamos calhar se formos para cima ou para baixo (igual nos dois casos)
def calculate_up_down_result(position):
    return {
        1: 3,
        3: 1,
        2: 4,
        4: 2
    }[position]

# Diz onde vamos calhar se formos para a esquerda ou para a direita (igual nos dois casos)
def calculate_left_right_result(position):
    return {
        1: 2,
        2: 1,
        3: 4,
        4: 3
    }[position]

# Diz o indice da matrix 16x16 dado um estado (exemplo (1,1) = 1 | (1,2) = 2)
def state_to_matrix_index(x, y):
    index = 0
    for row in range(4):
        for column in range(4):
            if row+1 == x and column+1 == y:
                return index
            else:
                index += 1

# Devolve os estados possiveis e as probabilidades dos movimentos da lebre
# Apenas a posicao da lebre e considerada (lobo ignorado)
def possible_hare_positions_and_probabilities(hare_position):

    up_down_state = calculate_up_down_result(hare_position)
    left_right_state = calculate_left_right_result(hare_position)

    return {
        up_down_state : 0.4*0.5,
        left_right_state : 0.4*0.5,
        hare_position: (0.6*0.5*2)
    }

# Devolve os estados possiveis e as probabilidades quando o lobo fica parado
def possible_Stay_wolf_positions_and_probabilities(wolf_position, hare_position):

    dict = possible_hare_positions_and_probabilities(hare_position)
    states_and_probabilities = {}

    for hare_state in dict:
        current_state = (wolf_position, hare_state)
        states_and_probabilities[current_state] = dict[hare_state]

    return states_and_probabilities

# Devolve os estados possiveis e as probabilidades quando o lobo (tenta) ir para cima ou para baixo (iguais)
def possible_Up_Down_wolf_positions_and_probabilities(wolf_position, hare_position):

    states_and_probabilities = possible_Stay_wolf_positions_and_probabilities(wolf_position, hare_position)

    for state in states_and_probabilities:
        states_and_probabilities[state] = states_and_probabilities[state] * 0.2

    new_wolf_position_if_succeeded = calculate_up_down_result(wolf_position)
    dict = possible_hare_positions_and_probabilities(hare_position)
    for hare_state in dict:
        current_state = (new_wolf_position_if_succeeded, hare_state)
        states_and_probabilities[current_state] = dict[hare_state] * 0.8

    return states_and_probabilities

# Devolve os estados possiveis e as probabilidades quando o lobo (tenta) ir para a esquerda ou para a direita (iguais)
# Apenas muda uma linha em relacao a funcao acima
# Possivel refatorizar codigo duplicado!!!
def possible_Left_Right_wolf_positions_and_probabilities(wolf_position, hare_position):

    states_and_probabilities = possible_Stay_wolf_positions_and_probabilities(wolf_position, hare_position)

    for state in states_and_probabilities:
        states_and_probabilities[state] = states_and_probabilities[state] * 0.2

    new_wolf_position_if_succeeded = calculate_left_right_result(wolf_position)
    dict = possible_hare_positions_and_probabilities(hare_position)
    for hare_state in dict:
        current_state = (new_wolf_position_if_succeeded, hare_state)
        states_and_probabilities[current_state] = dict[hare_state] * 0.8

    return states_and_probabilities

# -------------------------------------------------------
# -------------------------------------------------------
# -------------------------------------------------------

#Estados Possiveis
X = setup_possible_states()

#Acoes Possiveis
A = ["U", "D", "L", "R", "S"]

#Matrizes de probabilidade de transicao para cada acao
P_Up = np.zeros((16, 16))
P_Down = np.zeros((16, 16))

P_Left = np.zeros((16, 16))
P_Right = np.zeros((16, 16))

P_Stay = np.zeros((16, 16))

# -----------------------------------------------------------------
# Preenchimento das matrizes de probabilidade de transicao --------
# -----------------------------------------------------------------

def fill_P_Up_Down(wolf_position, hare_position):
    states_and_probabilities = possible_Up_Down_wolf_positions_and_probabilities(wolf_position, hare_position)
    current_row = state_to_matrix_index(wolf_position, hare_position)
    for state in states_and_probabilities:
        current_column = state_to_matrix_index(state[0], state[1])
        P_Up[current_row][current_column] = states_and_probabilities[state]
        P_Down[current_row][current_column] = states_and_probabilities[state]

def fill_P_Left_Right(wolf_position, hare_position):
    states_and_probabilities = possible_Left_Right_wolf_positions_and_probabilities(wolf_position, hare_position)
    current_row = state_to_matrix_index(wolf_position, hare_position)
    for state in states_and_probabilities:
        current_column = state_to_matrix_index(state[0], state[1])
        P_Left[current_row][current_column] = states_and_probabilities[state]
        P_Right[current_row][current_column] = states_and_probabilities[state]

def fill_P_Stay(wolf_position, hare_position):
    states_and_probabilities = possible_Stay_wolf_positions_and_probabilities(wolf_position, hare_position)
    current_row = state_to_matrix_index(wolf_position, hare_position)
    for state in states_and_probabilities:
        current_column = state_to_matrix_index(state[0], state[1])
        P_Stay[current_row][current_column] = states_and_probabilities[state]

def build_transition_probability_matrices():
    for row in range(4):
        for column in range(4):

            wolf_position = row+1
            hare_position = column+1

            fill_P_Up_Down(wolf_position, hare_position)
            fill_P_Left_Right(wolf_position, hare_position)
            fill_P_Stay(wolf_position, hare_position)
            
    return P_Up, P_Left, P_Stay


# Preencher Matrizes de Transicao para as acoes
build_transition_probability_matrices()

(array([[ 0.12,  0.04,  0.04,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.48,
          0.16,  0.16,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.04,  0.12,  0.  ,  0.04,  0.  ,  0.  ,  0.  ,  0.  ,  0.16,
          0.48,  0.  ,  0.16,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.04,  0.  ,  0.12,  0.04,  0.  ,  0.  ,  0.  ,  0.  ,  0.16,
          0.  ,  0.48,  0.16,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.04,  0.04,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.16,  0.16,  0.48,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.12,  0.04,  0.04,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.48,  0.16,  0.16,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.04,  0.12,  0.  ,  0.04,  0.  ,
          0.  ,  0.  ,  0.  ,  0.16,  0.48,  0.  ,  0.16],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.04,  0.  ,  0.12,  0.04,  0.  ,
          0.  ,  0.  ,  0.  ,  0.16,  0.  ,  0.48,  0.16],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.04,  0.04,  0.12,  0.  ,
          0

In [ ]:
#devolve vector custo da acçao up ou down
    if np.all(prob_matrix == P_Up) or np.all(prob_matrix == P_Down):
        cost_vector = costMatrix[:,0]
    
    #devolve vector custo da acçao left ou right
    elif np.all(prob_matrix == P_Left) or np.all(prob_matrix == P_Right):
        cost_vector = costMatrix[:,2]
        
    #devolve vector custo da acçao stay
    else:
        cost_vector = costMatrix[:,4]
    
    aux = ident - (np.dot(gamma, prob_matrix))

    invMatrix = inv(aux)
    
    return np.dot(invMatrix, cost_vector)



J_Up = calc_cost_to_go(P_Up)
J_Down = calc_cost_to_go(P_Down)
J_Left = calc_cost_to_go(P_Left)
J_Right = calc_cost_to_go(P_Right)
J_Stay = calc_cost_to_go(P_Stay)

print(J_Up)